rootProject.name = "leetcode"
include("twosums")
include("roman-to-int")
include("palindrome")
include("longest-common-prefix")
include("validparentheses")
include("merge-sorted-lists")
include("two-numbers")
include("longest-substring-non-repeating")
include("median-two-arrays")
include("reverse-integer")
include("atoi")